### ISSUE TITLE
Template Lang doesn't Work Well with JSON Files

### ISSUE THREAD

**Issue by 0xErgod** [heaths/gh-template#32]
I have been using `gh-template` to structure a template tree for my own use and my main two languages are TS/JS and python. While using the templating language in `package.json`, I noticed that the usage of double quotes (") conflicts with the JSON structure. I have tried using single quotes (') but it seems that the extension doesn't recognize it. Is there a fix or a way to do this?

**Comment by heaths** [comment]
I don't follow. Could you point me to a sample or produce a minimal sample inline here? A minimal repro would help me better understand and perhaps serve as a test to make sure the problem is fixed or at least a work around is available.

**Comment by 0xErgod** [comment]
Hey! 

I solved the problem by using (`) instead of (") inside JSON files. 

# The problem:

```json
{
  "name": "{{param "github.repo" | lowercase}}",
  "version": "1.0.0",
  "description": "{{param "description"}}",
  "main": "src/index.js",
  "type": "module",
  "scripts": {
    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js",
    "start": "node --experimental-specifier-resolution=node ."
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/{{param "github.owner"}}/{{param "github.repo"}}.git"
  },
  "author": "{{param "git.name"}}<{{param "git.email"}}>",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/{{param "github.owner"}}/{{param "github.repo"}}/issues"
  },
  "homepage": "https://github.com/{{param "github.owner"}}/{{param "github.repo"}}#readme",
  "devDependencies": {
    "jest": "^29.7.0"
  }
}
```

In this case, the double quotes are conflicting and messing up the interpretation of the `package.json` file. If you try to run the `npm` utility it will throw errors.

# The solution:

```json
{
  "name": "{{param `github.repo` | lowercase}}",
  "version": "1.0.0",
  "description": "{{param `description`}}",
  "main": "src/index.js",
  "type": "module",
  "scripts": {
    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js",
    "start": "node --experimental-specifier-resolution=node ."
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/{{param `github.owner`}}/{{param `github.repo`}}.git"
  },
  "author": "{{param `git.name`}}<{{param `git.email`}}>",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/{{param `github.owner`}}/{{param `github.repo`}}/issues"
  },
  "homepage": "https://github.com/{{param `github.owner`}}/{{param `github.repo`}}#readme",
  "devDependencies": {
    "jest": "^29.7.0"
  }
}

```

This way the `package.json` still works fine and the template lang is interpreted correctly by `gh-template`.
